import type { PrismaClient } from "@/app/generated/prisma/client";
import {
  DEFAULT_PROGRESS_STEPS,
  JINWOONG_PROJECT_ID,
  scoreToGrade,
} from "@/lib/jinwoong/constants";

const BASIC_INFO = {
  companyName: "진웅산업",
  representative: "김진웅",
  foundedYear: "1998",
  headquarters: "경기도 양주시",
  businessNumber: "",
  mainBusiness: "염료·화학 중간체 제조 및 산업용 부동산 보유",
  mainProducts: "산업용 염료, 화학 중간체",
  mainCustomers: "국내외 섬유·화학 관련 기업",
  employeeCount: "약 40명",
  capital: "",
  recentRevenue: "",
  operatingProfit: "",
  ebitda: "",
  majorAssets: "공장·토지 약 8,500㎡, 건물 약 3,200㎡",
  majorLiabilities: "",
  ownershipStructure: "창업주 일가 중심",
  askingPrice: "약 53억 원",
  saleEquity: "사업·자산 일괄 매각 검토",
  desiredTiming: "2026년 내",
};

const BUSINESS_ANALYSIS = {
  overview:
    "경기도 양주에 위치한 산업용 제조·부동산 자산 보유 기업으로, 기존 염료 제조시설과 토지를 일괄 매각하는 전략적 매각을 검토 중이다.",
  coreBusiness: "염료·화학 중간체 제조 및 산업용 부지 운영",
  productsServices: "산업용 염료, 관련 제조·보관 시설",
  revenueStructure: "제조 매출 + 보유 자산 가치",
  keyClients: "섬유·화학 관련 수요처",
  marketPosition: "지역 산업단지 내 제조·부지 보유 기업",
  competitiveness: "입지, 대지·건물 규모, 기존 제조 인프라",
  technology: "기존 염료 제조 설비 및 운영 노하우",
  facilities: "공장·토지 일괄, 양주 산업 입지",
  salesOrg: "기존 영업 조직 축소·매각 중심 전환",
  workforce: "소규모 운영 인력",
  ownerDependency: "창업주 중심 의사결정",
  growthPotential: "인수자 신규사업 목적의 부지·시설 활용 가능성",
  risks: "염료사업 승계 수요 제한, 환경·설비 노후화 가능성",
};

const FINANCIAL_ANALYSIS = {
  revenue3y: "비공개 / 내부 확인 필요",
  operatingProfit3y: "비공개 / 내부 확인 필요",
  ebitda3y: "비공개 / 내부 확인 필요",
  debtRatio: "내부 재무자료 확인 필요",
  cashFlow: "내부 재무자료 확인 필요",
  majorAssets: "공장·토지, 건물",
  nonOperatingAssets: "검토 중",
  normalizedEarnings: "검토 중",
  estimatedEnterpriseValue: "자산·입지 기반 평가 중심",
  fairSaleRange: "희망가 약 53억 원 기준 협의",
};

const SALE_POINTS = {
  buyerInterest:
    "산업용 부지·공장 확보, 양주 입지, 신규사업용 시설 전환 가능성",
  expectedSynergy: "인수자 기존 사업과의 생산·물류·고객 시너지",
  marketEntry: "수도권 북부 제조·물류 거점 확보",
  customerBase: "기존 거래선 승계 가능성은 제한적, 부지 활용이 핵심",
  techFacility: "기존 제조·보관 시설 활용 또는 재배치",
  competitorShare: "경쟁사 제거보다 자산·입지 확보 성격이 강함",
  realEstateValue: "대지·건물 가치와 용도 전환 잠재력",
  successionIssue: "후계·사업 재편에 따른 전략적 매각",
  improvementPotential: "시설 현대화, 신규 업종 전환, 운영 효율화",
};

type SampleTarget = {
  id: string;
  targetStage: number;
  companyName: string;
  companyNameEn: string;
  country: string;
  website: string;
  industry: string;
  companySize: string;
  revenue: string;
  employeeCount: number;
  targetReason: string;
  acquisitionProbability: string;
  aiScore: number;
  status: string;
  priority: number;
  hasContact: boolean;
  hasProposal: boolean;
  headquartersAddress: string;
  representativeName: string;
  mainBusiness: string;
  mainProducts: string;
  analysis: {
    businessSynergy: number;
    productSynergy: number;
    technologySynergy: number;
    customerSynergy: number;
    marketSynergy: number;
    financialCapacity: number;
    acquisitionHistory: number;
    acquisitionNeed: number;
    contactability: number;
    dealProbability: number;
    keySynergy: string;
    acquisitionLogic: string;
    concerns: string;
    followUpItems: string;
    approachStrategy: string;
    aiSummary: string;
  };
};

const SAMPLE_TARGETS: SampleTarget[] = [
  {
    id: "jw_target_01",
    targetStage: 1,
    companyName: "한빛케미칼",
    companyNameEn: "Hanbit Chemical",
    country: "KR",
    website: "https://example-hanbit.local",
    industry: "화학·염료",
    companySize: "중견",
    revenue: "약 800억",
    employeeCount: 220,
    targetReason: "동일 업종 생산능력 확장 및 양주 거점 확보 수요",
    acquisitionProbability: "HIGH",
    aiScore: 78,
    status: "PRIORITY_REVIEW",
    priority: 1,
    hasContact: true,
    hasProposal: false,
    headquartersAddress: "경기도 안산시",
    representativeName: "이한빛",
    mainBusiness: "산업용 화학제품 제조",
    mainProducts: "염료·중간체",
    analysis: {
      businessSynergy: 16,
      productSynergy: 12,
      technologySynergy: 11,
      customerSynergy: 12,
      marketSynergy: 10,
      financialCapacity: 11,
      acquisitionHistory: 8,
      acquisitionNeed: 8,
      contactability: 4,
      dealProbability: 4,
      keySynergy: "생산능력 확장 + 수도권 북부 입지",
      acquisitionLogic: "기존 라인 보완 및 물류 거점 확보",
      concerns: "환경 규제·설비 이전 비용",
      followUpItems: "최근 투자계획, 양주 이전 가능성",
      approachStrategy: "전략기획·생산본부장 경로로 접근",
      aiSummary: "동일 업종 확장형 매수 후보로 우선 검토 적합",
    },
  },
  {
    id: "jw_target_02",
    targetStage: 1,
    companyName: "동양색소",
    companyNameEn: "Dongyang Color",
    country: "KR",
    website: "https://example-dongyang.local",
    industry: "염료",
    companySize: "중소",
    revenue: "약 320억",
    employeeCount: 95,
    targetReason: "동일 고객군 보유, 설비 노후화로 부지·시설 수요 가능",
    acquisitionProbability: "MEDIUM",
    aiScore: 64,
    status: "ANALYZING",
    priority: 2,
    hasContact: false,
    hasProposal: false,
    headquartersAddress: "인천광역시",
    representativeName: "박동양",
    mainBusiness: "염료 제조",
    mainProducts: "섬유용 염료",
    analysis: {
      businessSynergy: 14,
      productSynergy: 11,
      technologySynergy: 9,
      customerSynergy: 10,
      marketSynergy: 8,
      financialCapacity: 7,
      acquisitionHistory: 5,
      acquisitionNeed: 7,
      contactability: 3,
      dealProbability: 3,
      keySynergy: "고객군 중복 + 시설 보완",
      acquisitionLogic: "노후 설비 대체 및 생산 집약",
      concerns: "자금 여력·규모 격차",
      followUpItems: "재무상태, 최근 CAPEX",
      approachStrategy: "대표 직접 접촉보다 실무 경로",
      aiSummary: "중위 적합도, 추가 재무 확인 필요",
    },
  },
  {
    id: "jw_target_03",
    targetStage: 2,
    companyName: "서해원료",
    companyNameEn: "Seohae Materials",
    country: "KR",
    website: "https://example-seohae.local",
    industry: "화학 원료",
    companySize: "중견",
    revenue: "약 1,200억",
    employeeCount: 310,
    targetReason: "전방 원료 공급망 통합 및 제조거점 확보",
    acquisitionProbability: "HIGH",
    aiScore: 81,
    status: "CONTACT_READY",
    priority: 1,
    hasContact: true,
    hasProposal: true,
    headquartersAddress: "충청남도 서산시",
    representativeName: "최서해",
    mainBusiness: "화학 원료 유통·가공",
    mainProducts: "산업용 원료",
    analysis: {
      businessSynergy: 17,
      productSynergy: 10,
      technologySynergy: 9,
      customerSynergy: 11,
      marketSynergy: 12,
      financialCapacity: 13,
      acquisitionHistory: 10,
      acquisitionNeed: 8,
      contactability: 4,
      dealProbability: 4,
      keySynergy: "공급망 수직통합",
      acquisitionLogic: "원료-제조 연결로 마진·안정성 확보",
      concerns: "본업 집중도, 비핵심 자산 인수 부담",
      followUpItems: "최근 M&A 이력, 신사업 조직",
      approachStrategy: "신사업·전략팀 티저 전달",
      aiSummary: "전후방 통합 논리가 명확한 고우선 후보",
    },
  },
  {
    id: "jw_target_04",
    targetStage: 2,
    companyName: "경기물류파트너스",
    companyNameEn: "Gyeonggi Logistics Partners",
    country: "KR",
    website: "https://example-glp.local",
    industry: "물류·창고",
    companySize: "중견",
    revenue: "약 950억",
    employeeCount: 480,
    targetReason: "양주·북부 물류거점 확장 수요",
    acquisitionProbability: "MEDIUM",
    aiScore: 58,
    status: "BASIC_RESEARCH",
    priority: 3,
    hasContact: false,
    hasProposal: false,
    headquartersAddress: "경기도 고양시",
    representativeName: "정경기",
    mainBusiness: "창고·물류센터 운영",
    mainProducts: "물류 서비스",
    analysis: {
      businessSynergy: 10,
      productSynergy: 5,
      technologySynergy: 4,
      customerSynergy: 8,
      marketSynergy: 12,
      financialCapacity: 10,
      acquisitionHistory: 7,
      acquisitionNeed: 6,
      contactability: 3,
      dealProbability: 3,
      keySynergy: "입지·창고 전환 가능성",
      acquisitionLogic: "제조보다 물류·보관 용도 전환",
      concerns: "용도변경·인허가",
      followUpItems: "부동산 활용 계획",
      approachStrategy: "부동산·개발 담당 접촉",
      aiSummary: "물류 전환형으로 제한적 적합",
    },
  },
  {
    id: "jw_target_05",
    targetStage: 3,
    companyName: "넥스트코팅",
    companyNameEn: "Next Coating",
    country: "KR",
    website: "https://example-nextcoating.local",
    industry: "표면처리·코팅",
    companySize: "중소",
    revenue: "약 180억",
    employeeCount: 70,
    targetReason: "유사 제조기술 기반 신사업 확장",
    acquisitionProbability: "MEDIUM",
    aiScore: 61,
    status: "ANALYZING",
    priority: 2,
    hasContact: false,
    hasProposal: false,
    headquartersAddress: "경기도 시흥시",
    representativeName: "오넥스트",
    mainBusiness: "산업용 코팅",
    mainProducts: "기능성 코팅재",
    analysis: {
      businessSynergy: 12,
      productSynergy: 10,
      technologySynergy: 12,
      customerSynergy: 8,
      marketSynergy: 7,
      financialCapacity: 6,
      acquisitionHistory: 4,
      acquisitionNeed: 7,
      contactability: 3,
      dealProbability: 3,
      keySynergy: "제조 기술·시설 전환",
      acquisitionLogic: "인접 기술로 라인 확장",
      concerns: "규모·자금",
      followUpItems: "기술 로드맵",
      approachStrategy: "기술총괄·대표 미팅",
      aiSummary: "기술 인접형 중순위 후보",
    },
  },
  {
    id: "jw_target_06",
    targetStage: 4,
    companyName: "한라산업홀딩스",
    companyNameEn: "Halla Industrial Holdings",
    country: "KR",
    website: "https://example-halla.local",
    industry: "제조 지주",
    companySize: "대기업/중견",
    revenue: "약 5,000억",
    employeeCount: 1200,
    targetReason: "사업 다각화 및 신규 제조거점 검토",
    acquisitionProbability: "HIGH",
    aiScore: 86,
    status: "PRIORITY_REVIEW",
    priority: 1,
    hasContact: true,
    hasProposal: true,
    headquartersAddress: "서울특별시",
    representativeName: "윤한라",
    mainBusiness: "제조 포트폴리오 운영",
    mainProducts: "다각화 제조",
    analysis: {
      businessSynergy: 18,
      productSynergy: 11,
      technologySynergy: 10,
      customerSynergy: 12,
      marketSynergy: 13,
      financialCapacity: 14,
      acquisitionHistory: 12,
      acquisitionNeed: 9,
      contactability: 4,
      dealProbability: 4,
      keySynergy: "포트폴리오 확장 + 입지",
      acquisitionLogic: "중규모 제조자산 bolt-on",
      concerns: "내부 승인 절차·경쟁입찰",
      followUpItems: "최근 인수 사례, 담당 조직",
      approachStrategy: "M&A·전략기획 티저",
      aiSummary: "자금력·의지 모두 높은 S급 후보",
    },
  },
  {
    id: "jw_target_07",
    targetStage: 5,
    companyName: "밸류업PE",
    companyNameEn: "ValueUp PE",
    country: "KR",
    website: "https://example-valueup.local",
    industry: "사모펀드",
    companySize: "투자회사",
    revenue: "-",
    employeeCount: 35,
    targetReason: "중소·중견 바이아웃 및 자산가치 상승형 투자",
    acquisitionProbability: "HIGH",
    aiScore: 74,
    status: "CONTACT_READY",
    priority: 1,
    hasContact: true,
    hasProposal: false,
    headquartersAddress: "서울특별시",
    representativeName: "강밸류",
    mainBusiness: "PE 투자",
    mainProducts: "바이아웃 펀드",
    analysis: {
      businessSynergy: 10,
      productSynergy: 6,
      technologySynergy: 5,
      customerSynergy: 6,
      marketSynergy: 10,
      financialCapacity: 14,
      acquisitionHistory: 13,
      acquisitionNeed: 8,
      contactability: 5,
      dealProbability: 4,
      keySynergy: "자산가치·운영개선",
      acquisitionLogic: "바이아웃 후 재배치·매각",
      concerns: "운영사 매칭 필요",
      followUpItems: "펀드 잔여 기간, 제조업 트랙레코드",
      approachStrategy: "딜팀 이메일·티저",
      aiSummary: "금융 바이어로 빠른 접촉 가능",
    },
  },
  {
    id: "jw_target_08",
    targetStage: 5,
    companyName: "승계파트너스",
    companyNameEn: "Succession Partners",
    country: "KR",
    website: "https://example-succession.local",
    industry: "투자·승계",
    companySize: "투자회사",
    revenue: "-",
    employeeCount: 20,
    targetReason: "기업 승계·구조개선 투자 전문",
    acquisitionProbability: "MEDIUM",
    aiScore: 69,
    status: "BASIC_RESEARCH",
    priority: 2,
    hasContact: false,
    hasProposal: false,
    headquartersAddress: "서울특별시",
    representativeName: "임승계",
    mainBusiness: "승계 투자",
    mainProducts: "구조개선 펀드",
    analysis: {
      businessSynergy: 9,
      productSynergy: 5,
      technologySynergy: 4,
      customerSynergy: 5,
      marketSynergy: 9,
      financialCapacity: 12,
      acquisitionHistory: 11,
      acquisitionNeed: 8,
      contactability: 4,
      dealProbability: 3,
      keySynergy: "승계형 딜 구조",
      acquisitionLogic: "오너 엑시트 맞춤 구조",
      concerns: "티켓 사이즈",
      followUpItems: "투자 기준 금액",
      approachStrategy: "승계 전문 파트너 접촉",
      aiSummary: "승계 스토리와 정합",
    },
  },
  {
    id: "jw_target_09",
    targetStage: 6,
    companyName: "Nippon Dye Works",
    companyNameEn: "Nippon Dye Works",
    country: "JP",
    website: "https://example-ndw.local",
    industry: "염료·화학",
    companySize: "중견",
    revenue: "약 ¥45B",
    employeeCount: 650,
    targetReason: "한국 생산기지·고객망 확보 수요 가능",
    acquisitionProbability: "MEDIUM",
    aiScore: 72,
    status: "ANALYZING",
    priority: 2,
    hasContact: false,
    hasProposal: false,
    headquartersAddress: "Osaka, Japan",
    representativeName: "-",
    mainBusiness: "염료 제조",
    mainProducts: "산업용 염료",
    analysis: {
      businessSynergy: 15,
      productSynergy: 12,
      technologySynergy: 11,
      customerSynergy: 10,
      marketSynergy: 11,
      financialCapacity: 11,
      acquisitionHistory: 7,
      acquisitionNeed: 7,
      contactability: 2,
      dealProbability: 3,
      keySynergy: "한국 거점 확보",
      acquisitionLogic: "해외 생산·시장 접근",
      concerns: "크로스보더 실사·언어",
      followUpItems: "한국 진출 계획 공개정보",
      approachStrategy: "해외사업·IR 경로",
      aiSummary: "해외 전략 투자자 후보",
    },
  },
  {
    id: "jw_target_10",
    targetStage: 7,
    companyName: "김도경 (개인 인수 후보)",
    companyNameEn: "Kim Dokyung",
    country: "KR",
    website: "",
    industry: "개인·경영자",
    companySize: "개인",
    revenue: "-",
    employeeCount: 0,
    targetReason: "화학·제조 경력 경영자, 직접 경영 인수 의사 탐문",
    acquisitionProbability: "LOW",
    aiScore: 47,
    status: "NEW",
    priority: 4,
    hasContact: false,
    hasProposal: false,
    headquartersAddress: "서울특별시",
    representativeName: "김도경",
    mainBusiness: "개인 투자·경영",
    mainProducts: "-",
    analysis: {
      businessSynergy: 8,
      productSynergy: 6,
      technologySynergy: 5,
      customerSynergy: 4,
      marketSynergy: 5,
      financialCapacity: 5,
      acquisitionHistory: 3,
      acquisitionNeed: 6,
      contactability: 4,
      dealProbability: 2,
      keySynergy: "직접 경영·현장 이해",
      acquisitionLogic: "오너 경영 승계형",
      concerns: "자금 조달",
      followUpItems: "자금 출처·파트너 PE 유무",
      approachStrategy: "소개 네트워크 경유",
      aiSummary: "개인 후보로 후순위 모니터링",
    },
  },
];

export async function seedJinwoongMvp(prisma: PrismaClient) {
  await prisma.jinwoongProject.upsert({
    where: { id: JINWOONG_PROJECT_ID },
    update: {
      projectName: "Jinwww 매각 프로젝트",
      companyName: "진웅산업",
      description:
        "진웅산업 전략적 매각 및 잠재 매수자 발굴 프로젝트",
      status: "ACTIVE",
      progressSteps: DEFAULT_PROGRESS_STEPS,
      lastUpdatedAt: new Date(),
    },
    create: {
      id: JINWOONG_PROJECT_ID,
      projectName: "Jinwww 매각 프로젝트",
      companyName: "진웅산업",
      description:
        "진웅산업 전략적 매각 및 잠재 매수자 발굴 프로젝트",
      status: "ACTIVE",
      progressSteps: DEFAULT_PROGRESS_STEPS,
      lastUpdatedAt: new Date(),
    },
  });

  await prisma.jinwoongCompanyProfile.upsert({
    where: { projectId: JINWOONG_PROJECT_ID },
    update: {
      basicInfo: BASIC_INFO,
      businessAnalysis: BUSINESS_ANALYSIS,
      financialAnalysis: FINANCIAL_ANALYSIS,
      salePoints: SALE_POINTS,
    },
    create: {
      projectId: JINWOONG_PROJECT_ID,
      basicInfo: BASIC_INFO,
      businessAnalysis: BUSINESS_ANALYSIS,
      financialAnalysis: FINANCIAL_ANALYSIS,
      salePoints: SALE_POINTS,
    },
  });

  for (const sample of SAMPLE_TARGETS) {
    const grade = scoreToGrade(sample.aiScore);
    await prisma.jinwoongTarget.upsert({
      where: { id: sample.id },
      update: {
        targetStage: sample.targetStage,
        companyName: sample.companyName,
        companyNameEn: sample.companyNameEn,
        country: sample.country,
        website: sample.website || null,
        websiteDomain: sample.website
          ? sample.website.replace(/^https?:\/\//, "").split("/")[0]
          : null,
        industry: sample.industry,
        companySize: sample.companySize,
        revenue: sample.revenue,
        employeeCount: sample.employeeCount || null,
        targetReason: sample.targetReason,
        acquisitionProbability: sample.acquisitionProbability,
        aiScore: sample.aiScore,
        aiGrade: grade,
        status: sample.status,
        priority: sample.priority,
        hasContact: sample.hasContact,
        hasProposal: sample.hasProposal,
        headquartersAddress: sample.headquartersAddress,
        representativeName: sample.representativeName,
        mainBusiness: sample.mainBusiness,
        mainProducts: sample.mainProducts,
        lastSearchedAt: new Date(),
      },
      create: {
        id: sample.id,
        projectId: JINWOONG_PROJECT_ID,
        targetStage: sample.targetStage,
        companyName: sample.companyName,
        companyNameEn: sample.companyNameEn,
        country: sample.country,
        website: sample.website || null,
        websiteDomain: sample.website
          ? sample.website.replace(/^https?:\/\//, "").split("/")[0]
          : null,
        industry: sample.industry,
        companySize: sample.companySize,
        revenue: sample.revenue,
        employeeCount: sample.employeeCount || null,
        targetReason: sample.targetReason,
        acquisitionProbability: sample.acquisitionProbability,
        aiScore: sample.aiScore,
        aiGrade: grade,
        status: sample.status,
        priority: sample.priority,
        hasContact: sample.hasContact,
        hasProposal: sample.hasProposal,
        headquartersAddress: sample.headquartersAddress,
        representativeName: sample.representativeName,
        mainBusiness: sample.mainBusiness,
        mainProducts: sample.mainProducts,
        lastSearchedAt: new Date(),
      },
    });

    const a = sample.analysis;
    const totalScore =
      a.businessSynergy +
      a.productSynergy +
      a.technologySynergy +
      a.customerSynergy +
      a.marketSynergy +
      a.financialCapacity +
      a.acquisitionHistory +
      a.acquisitionNeed +
      a.contactability +
      a.dealProbability;

    await prisma.jinwoongTargetAnalysis.upsert({
      where: { targetId: sample.id },
      update: {
        ...a,
        totalScore,
        grade: scoreToGrade(totalScore),
        analyzedAt: new Date(),
      },
      create: {
        targetId: sample.id,
        ...a,
        totalScore,
        grade: scoreToGrade(totalScore),
        analyzedAt: new Date(),
      },
    });
  }
}
