/**
 * Idempotent Turso/SQLite DDL derived from prisma/schema.prisma.
 * CREATE IF NOT EXISTS — safe to re-run; does not drop or delete data.
 * Regenerate with:
 *   npx prisma migrate diff --from-empty --to-schema prisma/schema.prisma --script
 * then convert to IF NOT EXISTS and JSONB→JSON.
 */
export const TURSO_SCHEMA_DDL_STATEMENTS: string[] = [
  `CREATE TABLE IF NOT EXISTS "Project" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "name" TEXT NOT NULL,
    "companyName" TEXT NOT NULL,
    "projectType" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'ACTIVE',
    "location" TEXT,
    "askingPrice" BIGINT,
    "summary" TEXT,
    "propertyType" TEXT,
    "landArea" TEXT,
    "buildingArea" TEXT,
    "desiredClosingDate" DATETIME,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS "Company" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "companyName" TEXT NOT NULL,
    "normalizedName" TEXT NOT NULL,
    "businessNumber" TEXT,
    "corporateNumber" TEXT,
    "industryGroup" TEXT,
    "detailedIndustry" TEXT,
    "website" TEXT,
    "websiteDomain" TEXT,
    "address" TEXT,
    "normalizedAddress" TEXT,
    "region" TEXT,
    "representativeName" TEXT,
    "mainPhone" TEXT,
    "generalEmail" TEXT,
    "employeeCount" INTEGER,
    "estimatedRevenue" TEXT,
    "currentFacilityType" TEXT,
    "status" TEXT NOT NULL DEFAULT 'NEW',
    "verificationMemo" TEXT,
    "lastVerifiedAt" DATETIME,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS "ProjectCompany" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "projectId" TEXT NOT NULL,
    "companyId" TEXT NOT NULL,
    "targetGrade" TEXT NOT NULL DEFAULT 'C',
    "fitScore" INTEGER NOT NULL DEFAULT 0,
    "financialScore" INTEGER NOT NULL DEFAULT 0,
    "locationScore" INTEGER NOT NULL DEFAULT 0,
    "facilityNeedScore" INTEGER NOT NULL DEFAULT 0,
    "expansionSignalScore" INTEGER NOT NULL DEFAULT 0,
    "decisionMakerScore" INTEGER NOT NULL DEFAULT 0,
    "recommendedUse" TEXT,
    "targetingReason" TEXT,
    "riskFactors" TEXT,
    "reviewStatus" TEXT NOT NULL DEFAULT 'PENDING',
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "ProjectCompany_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "Project" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "ProjectCompany_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company" ("id") ON DELETE CASCADE ON UPDATE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS "Contact" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "companyId" TEXT NOT NULL,
    "contactName" TEXT,
    "jobTitle" TEXT,
    "department" TEXT,
    "email" TEXT,
    "mobile" TEXT,
    "source" TEXT,
    "verified" BOOLEAN NOT NULL DEFAULT false,
    "lastVerifiedAt" DATETIME,
    "contactPermissionStatus" TEXT NOT NULL DEFAULT 'UNKNOWN',
    CONSTRAINT "Contact_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company" ("id") ON DELETE CASCADE ON UPDATE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS "CompanySource" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "companyId" TEXT NOT NULL,
    "sourceType" TEXT NOT NULL,
    "sourceUrl" TEXT,
    "searchKeyword" TEXT,
    "discoveredReason" TEXT,
    "provider" TEXT,
    "externalId" TEXT,
    "rawMetadata" JSON,
    "sourceConfidence" TEXT,
    "lastVerifiedAt" DATETIME,
    "collectedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "CompanySource_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company" ("id") ON DELETE CASCADE ON UPDATE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS "DailyActivity" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "projectId" TEXT NOT NULL,
    "activityDate" DATETIME NOT NULL,
    "rawText" TEXT NOT NULL,
    "summary" TEXT,
    "activityType" TEXT NOT NULL DEFAULT 'OTHER',
    "result" TEXT,
    "contactedCompanyIds" JSON,
    "aiAnalysis" JSON,
    "nextActionDate" DATETIME,
    "memo" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "DailyActivity_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "Project" ("id") ON DELETE CASCADE ON UPDATE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS "TargetExpansionSuggestion" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "projectId" TEXT NOT NULL,
    "dailyActivityId" TEXT,
    "segmentName" TEXT NOT NULL,
    "reason" TEXT NOT NULL,
    "evidence" JSON,
    "recommendationScore" INTEGER NOT NULL DEFAULT 0,
    "priority" TEXT NOT NULL DEFAULT 'MEDIUM',
    "status" TEXT NOT NULL DEFAULT 'PENDING',
    "proposedRegions" JSON,
    "proposedKeywords" JSON,
    "proposedTargetCount" INTEGER NOT NULL DEFAULT 0,
    "reviewedAt" DATETIME,
    "approvedAt" DATETIME,
    "rejectedReason" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "TargetExpansionSuggestion_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "Project" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "TargetExpansionSuggestion_dailyActivityId_fkey" FOREIGN KEY ("dailyActivityId") REFERENCES "DailyActivity" ("id") ON DELETE SET NULL ON UPDATE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS "TargetCollectionJob" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "projectId" TEXT NOT NULL,
    "suggestionId" TEXT,
    "jobType" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'QUEUED',
    "searchPlan" JSON NOT NULL,
    "requestedCount" INTEGER NOT NULL DEFAULT 0,
    "collectedCount" INTEGER NOT NULL DEFAULT 0,
    "acceptedCount" INTEGER NOT NULL DEFAULT 0,
    "duplicateCount" INTEGER NOT NULL DEFAULT 0,
    "rejectedCount" INTEGER NOT NULL DEFAULT 0,
    "errorMessage" TEXT,
    "jobStats" JSON,
    "progressPercent" INTEGER,
    "currentStep" TEXT,
    "currentQuery" TEXT,
    "processedQueries" INTEGER NOT NULL DEFAULT 0,
    "totalQueries" INTEGER NOT NULL DEFAULT 0,
    "apiCallCount" INTEGER NOT NULL DEFAULT 0,
    "rawResultCount" INTEGER NOT NULL DEFAULT 0,
    "reviewRequiredCount" INTEGER NOT NULL DEFAULT 0,
    "lastProgressAt" DATETIME,
    "lastMessage" TEXT,
    "startedAt" DATETIME,
    "completedAt" DATETIME,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "TargetCollectionJob_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "Project" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "TargetCollectionJob_suggestionId_fkey" FOREIGN KEY ("suggestionId") REFERENCES "TargetExpansionSuggestion" ("id") ON DELETE SET NULL ON UPDATE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS "DiscoveredCandidate" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "projectId" TEXT NOT NULL,
    "collectionJobId" TEXT,
    "provider" TEXT NOT NULL,
    "externalId" TEXT,
    "companyName" TEXT NOT NULL,
    "normalizedName" TEXT NOT NULL,
    "industryGroup" TEXT,
    "segmentName" TEXT,
    "categoryName" TEXT,
    "categoryGroupName" TEXT,
    "phone" TEXT,
    "address" TEXT,
    "roadAddress" TEXT,
    "region" TEXT,
    "placeUrl" TEXT,
    "searchKeyword" TEXT,
    "sourceConfidence" TEXT,
    "validationStatus" TEXT NOT NULL DEFAULT 'DISCOVERED',
    "validationScore" INTEGER NOT NULL DEFAULT 0,
    "rejectionReason" TEXT,
    "duplicateOfId" TEXT,
    "isDuplicate" BOOLEAN NOT NULL DEFAULT false,
    "fitScore" INTEGER NOT NULL DEFAULT 0,
    "targetGrade" TEXT,
    "recommendedUse" TEXT,
    "targetingReason" TEXT,
    "rawMetadata" JSON,
    "discoveredAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "reviewedAt" DATETIME,
    "importedAt" DATETIME,
    "importedCompanyId" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "DiscoveredCandidate_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "Project" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "DiscoveredCandidate_collectionJobId_fkey" FOREIGN KEY ("collectionJobId") REFERENCES "TargetCollectionJob" ("id") ON DELETE SET NULL ON UPDATE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS "ActivityLog" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "projectId" TEXT,
    "companyId" TEXT,
    "projectCompanyId" TEXT,
    "outreachId" TEXT,
    "collectionJobId" TEXT,
    "eventType" TEXT NOT NULL,
    "actorType" TEXT NOT NULL DEFAULT 'SYSTEM',
    "actorId" TEXT,
    "summary" TEXT NOT NULL,
    "metadata" JSON,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "ActivityLog_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "Project" ("id") ON DELETE SET NULL ON UPDATE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS "Outreach" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "projectId" TEXT NOT NULL,
    "companyId" TEXT NOT NULL,
    "projectCompanyId" TEXT,
    "contactId" TEXT,
    "emailType" TEXT NOT NULL,
    "subject" TEXT NOT NULL,
    "emailBody" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'DRAFT',
    "approvalStatus" TEXT NOT NULL DEFAULT 'DRAFT',
    "templateType" TEXT,
    "generationMethod" TEXT,
    "draftVersion" INTEGER NOT NULL DEFAULT 1,
    "contentHash" TEXT,
    "approvedAt" DATETIME,
    "approvedBy" TEXT,
    "rejectionReason" TEXT,
    "scheduledAt" DATETIME,
    "sentAt" DATETIME,
    "repliedAt" DATETIME,
    "replyType" TEXT,
    "replySummary" TEXT,
    "replySentiment" TEXT,
    "nextActionDate" DATETIME,
    "provider" TEXT,
    "providerMessageId" TEXT,
    "failureReason" TEXT,
    "errorMessage" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "Outreach_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "Project" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "Outreach_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "Outreach_contactId_fkey" FOREIGN KEY ("contactId") REFERENCES "Contact" ("id") ON DELETE SET NULL ON UPDATE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS "AppSetting" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "key" TEXT NOT NULL,
    "value" JSON NOT NULL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS "SuppressionList" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "email" TEXT NOT NULL,
    "companyName" TEXT,
    "reason" TEXT,
    "optedOutAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "source" TEXT
  )`,
  `CREATE TABLE IF NOT EXISTS "ProjectInsight" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "projectId" TEXT NOT NULL,
    "category" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "summary" TEXT,
    "keyIssues" JSON,
    "saleImpact" TEXT,
    "opportunities" JSON,
    "risks" JSON,
    "sourceNotes" TEXT,
    "sourceUrls" JSON,
    "content" JSON,
    "lastUpdatedAt" DATETIME,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "ProjectInsight_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "Project" ("id") ON DELETE CASCADE ON UPDATE CASCADE
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS "Company_businessNumber_key" ON "Company"("businessNumber")`,
  `CREATE UNIQUE INDEX IF NOT EXISTS "ProjectCompany_projectId_companyId_key" ON "ProjectCompany"("projectId", "companyId")`,
  `CREATE INDEX IF NOT EXISTS "CompanySource_companyId_provider_externalId_idx" ON "CompanySource"("companyId", "provider", "externalId")`,
  `CREATE INDEX IF NOT EXISTS "CompanySource_companyId_sourceUrl_searchKeyword_idx" ON "CompanySource"("companyId", "sourceUrl", "searchKeyword")`,
  `CREATE INDEX IF NOT EXISTS "DiscoveredCandidate_projectId_validationStatus_idx" ON "DiscoveredCandidate"("projectId", "validationStatus")`,
  `CREATE INDEX IF NOT EXISTS "DiscoveredCandidate_provider_externalId_idx" ON "DiscoveredCandidate"("provider", "externalId")`,
  `CREATE INDEX IF NOT EXISTS "DiscoveredCandidate_collectionJobId_idx" ON "DiscoveredCandidate"("collectionJobId")`,
  `CREATE INDEX IF NOT EXISTS "ActivityLog_projectId_createdAt_idx" ON "ActivityLog"("projectId", "createdAt")`,
  `CREATE INDEX IF NOT EXISTS "ActivityLog_eventType_createdAt_idx" ON "ActivityLog"("eventType", "createdAt")`,
  `CREATE INDEX IF NOT EXISTS "ActivityLog_companyId_idx" ON "ActivityLog"("companyId")`,
  `CREATE UNIQUE INDEX IF NOT EXISTS "AppSetting_key_key" ON "AppSetting"("key")`,
  `CREATE UNIQUE INDEX IF NOT EXISTS "SuppressionList_email_key" ON "SuppressionList"("email")`,
  `CREATE UNIQUE INDEX IF NOT EXISTS "ProjectInsight_projectId_category_key" ON "ProjectInsight"("projectId", "category")`,
  `CREATE INDEX IF NOT EXISTS "ProjectInsight_projectId_idx" ON "ProjectInsight"("projectId")`,
  `CREATE INDEX IF NOT EXISTS "ProjectInsight_category_idx" ON "ProjectInsight"("category")`,
];

/** 기존 TargetCollectionJob 테이블에 진행상태 컬럼 추가 (idempotent: duplicate column 무시) */
export const TURSO_SCHEMA_ALTER_STATEMENTS: string[] = [
  `ALTER TABLE "TargetCollectionJob" ADD COLUMN "progressPercent" INTEGER`,
  `ALTER TABLE "TargetCollectionJob" ADD COLUMN "currentStep" TEXT`,
  `ALTER TABLE "TargetCollectionJob" ADD COLUMN "currentQuery" TEXT`,
  `ALTER TABLE "TargetCollectionJob" ADD COLUMN "processedQueries" INTEGER NOT NULL DEFAULT 0`,
  `ALTER TABLE "TargetCollectionJob" ADD COLUMN "totalQueries" INTEGER NOT NULL DEFAULT 0`,
  `ALTER TABLE "TargetCollectionJob" ADD COLUMN "apiCallCount" INTEGER NOT NULL DEFAULT 0`,
  `ALTER TABLE "TargetCollectionJob" ADD COLUMN "rawResultCount" INTEGER NOT NULL DEFAULT 0`,
  `ALTER TABLE "TargetCollectionJob" ADD COLUMN "reviewRequiredCount" INTEGER NOT NULL DEFAULT 0`,
  `ALTER TABLE "TargetCollectionJob" ADD COLUMN "lastProgressAt" DATETIME`,
  `ALTER TABLE "TargetCollectionJob" ADD COLUMN "lastMessage" TEXT`,
];
